name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "customer-service/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Unit Tests
        run: mvn test

      - name: Build Docker image
        run: mvn spring-boot:build-image -Pprod

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/food.ordering.system.customer.service:latest

      - name: Clean up
        run: docker logout

